### ISSUE TITLE
怀疑一处拼写错误造成的图片无法显示

### ISSUE THREAD

**Issue by playmsg** [hzxie/Google-Font-Fix#7]
google-font-fix-options.php 第80行：
`<option value="//gravatar.luoli.net/avatar">`
此处疑为luoli.net为loli.net的拼写错误。修改为loli.net访问头像正常，既如下：
`<option value="//gravatar.loli.net/avatar">`
luoli为萝莉的拼音，顺手既能打出代替luoli，作者lsp无疑了。；）

**Comment by hzxie** [comment]
hhhhhhh 可能我当时看错了。你提一个PR呗？

**Comment by playmsg** [comment]
PR已提……不提我都忘了自己github密码。
